### ISSUE TITLE
Fix failing null calculations

### ISSUE THREAD

**Issue by elphick** [elphick/pandera-utils#12]
An empty calculation from a yaml entry (shown below) will attempt to execute and fail

```
columns:
   my_column:
      metadata:
         pandera_utils:
            calculation: null
```

We need to bypass the calculation when None/null to allow such entries in the yaml schema file.
